# Generated by Django 5.0.3 on 2024-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_modalidade_aluno_modalidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
