# Generated by Django 5.0.3 on 2024-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_cidade_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='fundacao_cidade',
            field=models.DateField(default='2023-02-10'),
            preserve_default=False,
        ),
    ]
